---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: test-source-container
  labels:
    build.appstudio.redhat.com/pipeline: "bonfire"
spec:
  params:
    - name: URL
      default: 'https://github.com/scoheb/test-source-container'
    - name: REVISION
      default: 'main'
    - name: SNAPSHOT
      type: string
      description: |
        Spec section of an ApplicationSnapshot resource. Not all fields of the
        resource are required. A minimal example:
          {
            "components": [
              {
                "containerImage": "quay.io/example/repo:latest"
              }
            ]
          }
        Each "containerImage" in the "components" array is validated.
  tasks:
    - name: test-source-container
      params:
        - name: SNAPSHOT
          value: "$(params.SNAPSHOT)"
      taskRef:
        resolver: git
        params:
          - name: url
            value: "$(params.URL)"
          - name: revision
            value: "$(params.REVISION)"
          - name: pathInRepo
            value: tasks/test-source-container.yaml
