apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/gbenhaim/tekton-insights?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-event: '[pull_request]'
    pipelinesascode.tekton.dev/on-target-branch: '[main]'
  labels:
    appstudio.openshift.io/application: tekton-insights
    appstudio.openshift.io/component: tekton-insights
  name: test-source-container
  namespace: shebert-tenant
spec:
  params:
  - name: URL
    value: 'https://github.com/scoheb/test-source-container'
  - name: REVISION
    value: 'main'
  - name: SNAPSHOT
    value: |
      {
        "application": "rhel-bootc",
        "components": [
            {
                "name": "rhel-bootc",
                "containerImage": "quay.io/redhat-user-workloads/rhel-bootc-tenant/rhel-bootc-9-4/rhel-bootc-9-4@sha256:ff57c770d283c1dcd750ad4b64f1386b7053b36b6d1a3ea60d4a68ce0473780e",
                "source": {
                    "git": {
                        "url": "https://gitlab.com/redhat/rhel/bifrost/rhel-bootc",
                        "revision": "779f7d7aad51741f8ed4834ebd8e8cd1ee610a20"
                    }
                }
            }
        ],
        "artifacts": {}
      }
  pipelineRef:
      resolver: git
      params:
      - name: url
        value: 'https://github.com/scoheb/test-source-container'
      - name: revision
        value: 'main'
      - name: pathInRepo
        value: pipelines/basic.yaml
    
