apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/gbenhaim/tekton-insights?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-event: '[pull_request]'
    pipelinesascode.tekton.dev/on-target-branch: '[main]'
  labels:
    appstudio.openshift.io/application: tekton-insights
    appstudio.openshift.io/component: tekton-insights
  name: tekton-insights-on-pull-request
  namespace: shebert-tenant
spec:
  params:
  - name: URL
    value: 'https://github.com/scoheb/test-source-container'
  - name: REVISION
    value: 'main'
  - name: SNAPSHOT
    value: |
      {
        "application": "insights-ingress-go",
        "components": [
            {
                "name": "ingress",
                "containerImage": "quay.io/redhat-user-workloads/rhtap-migration-tenant/insights-ingress-go/ingress:build-f303d-1712948816@sha256:12e29022a7d4736dd3c8377aa9d89d66d52b4f7566f0137d49295e4487a3b992",
                "source": {
                    "git": {
                        "url": "https://github.com/ernesgonzalez33/insights-ingress-go",
                        "revision": "1d5de29b99c26dd432f289d3408590269d0f58a6"
                    }
                }
            }
        ],
        "artifacts": {}
      }
  pipelineRef:
      resolver: git
      params:
      - name: url
        value: 'https://github.com/scoheb/test-source-container'
      - name: revision
        value: 'main'
      - name: pathInRepo
        value: pipelines/basic.yaml
    
